(function(){
 const files='abcdefgh', pieceCode={K:'wK',Q:'wQ',R:'wR',B:'wB',N:'wN',P:'wP',k:'bK',q:'bQ',r:'bR',b:'bB',n:'bN',p:'bP'};
 function coords(s){return [files.indexOf(s[0]),8-Number(s[1])]} function sq(x,y){return files[x]+(8-y)}
 class PuzzleEngine{
  constructor(el,handlers={}){this.el=el;this.handlers=handlers;this.position={};this.orientation='white';this.selected=null;this.last=[];this.wrong=[];this.locked=true;this.dragFrom=null}
  loadFen(fen){this.position={};let rows=fen.split(' ')[0].split('/');rows.forEach((row,y)=>{let x=0;for(let c of row){if(/\d/.test(c))x+=+c;else{this.position[sq(x,y)]=c;x++}}});this.render()}
  setOrientation(o){this.orientation=o;this.render()}
  move(uci){let from=uci.slice(0,2),to=uci.slice(2,4),p=this.position[from];if(!p)return false;delete this.position[from];if((p==='K'||p==='k')&&Math.abs(coords(from)[0]-coords(to)[0])===2){let kingSide=to[0]==='g',rank=from[1],rf=(kingSide?'h':'a')+rank,rt=(kingSide?'f':'d')+rank;this.position[rt]=this.position[rf];delete this.position[rf]}if((p==='P'||p==='p')&&from[0]!==to[0]&&!this.position[to])delete this.position[to[0]+from[1]];if(uci[4])p=p===p.toUpperCase()?uci[4].toUpperCase():uci[4];this.position[to]=p;this.last=[from,to];this.selected=null;this.render();return true}
  pseudoMoves(from){let p=this.position[from];if(!p)return[];let white=p===p.toUpperCase(),[x,y]=coords(from),out=[];const add=(nx,ny,slide=false)=>{if(nx<0||nx>7||ny<0||ny>7)return false;let t=sq(nx,ny),q=this.position[t];if(!q){out.push(t);return slide}if((q===q.toUpperCase())!==white)out.push(t);return false};let u=p.toLowerCase();if(u==='p'){let d=white?-1:1;if(!this.position[sq(x,y+d)]){add(x,y+d);let start=white?6:1;if(y===start&&!this.position[sq(x,y+2*d)])add(x,y+2*d)};for(let dx of[-1,1]){let t=sq(x+dx,y+d);if(this.position[t]||t===this.enPassant)add(x+dx,y+d)}}else if(u==='n'){for(let[a,b]of[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]])add(x+a,y+b)}else if(u==='k'){for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)if(a||b)add(x+a,y+b);add(x+2,y);add(x-2,y)}else{let dirs=u==='b'?[[1,1],[-1,1],[1,-1],[-1,-1]]:u==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[-1,1],[1,-1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];for(let[a,b]of dirs){let n=1;while(add(x+a*n,y+b*n,true))n++}}return out}
  render(){this.el.innerHTML='';let order=[];for(let y=0;y<8;y++)for(let x=0;x<8;x++)order.push(this.orientation==='white'?sq(x,y):sq(7-x,7-y));for(let i=0;i<64;i++){let s=order[i],[x,y]=coords(s),d=document.createElement('div');d.className='square '+((x+y)%2?'dark':'light');d.dataset.square=s;d.setAttribute('role','gridcell');if(this.last.includes(s))d.classList.add('last');if(this.selected===s)d.classList.add('selected');if(this.wrong.includes(s))d.classList.add('wrong');if(this.selected&&this.pseudoMoves(this.selected).includes(s))d.classList.add('legal');let p=this.position[s];if(p){d.classList.add('occupied');let e=document.createElement('img');e.className='piece';e.src='assets/pieces/staunty/'+pieceCode[p]+'.svg';e.alt='';e.draggable=true;e.addEventListener('dragstart',ev=>{this.dragFrom=s;ev.dataTransfer.setData('text/plain',s)});d.append(e)}if(window.appSettings?.coordinates){let visualFile=i%8,visualRank=Math.floor(i/8);if(visualFile===0){let c=document.createElement('span');c.className='coord rank';c.textContent=s[1];d.append(c)}if(visualRank===7){let c=document.createElement('span');c.className='coord file';c.textContent=s[0];d.append(c)}}d.addEventListener('click',()=>this.click(s));d.addEventListener('dragover',e=>e.preventDefault());d.addEventListener('drop',e=>{e.preventDefault();this.tryMove(this.dragFrom,s)});this.el.append(d)}}
  click(s){if(this.locked)return;if(this.selected){if(s===this.selected){this.selected=null;this.render();return}if(this.pseudoMoves(this.selected).includes(s)){this.tryMove(this.selected,s);return}}let p=this.position[s],white=p&&p===p.toUpperCase();if(p&&((this.orientation==='white')===white)){this.selected=s;this.render()}}
  tryMove(from,to){if(this.locked||!from)return;let promotion='';let p=this.position[from];if((p==='P'&&to[1]==='8')||(p==='p'&&to[1]==='1'))promotion='q';this.handlers.onUserMove?.(from+to+promotion)}
  markWrong(from,to){this.wrong=[from,to];this.render();setTimeout(()=>{this.wrong=[];this.render()},700)}
 }
 window.PuzzleEngine=PuzzleEngine;
})();
